### ISSUE TITLE
Uninstall a package from a remote repository

### ISSUE THREAD

**Issue by auryannn** [DannyBen/rush-cli#75]
The `rush snatch` command runs the `main` script of the package, but it could be
interesting to have some option to run the `undo` script too.

**Comment by DannyBen** [comment]
Hmm. I can see the value in that. Let me see if I can add it without adverse side effects.

**Comment by DannyBen** [comment]
`rush snatch PACKAGE --undo` - makes sense? If so, it is implemented in #76 if you want to give it a shot.

**Comment by auryannn** [comment]
I think using `--undo` along with `--force` wouldn't make much sense. Perhaps
limiting the use of `--force` solely for installations would be better. What do
you think?

**Comment by DannyBen** [comment]
No need. `--force` and `--verbose` have no meaning unless the package author has implemented it.
It is benign otherwise.

**Comment by auryannn** [comment]
Oh, I didn't know that, so it's perfect, it was exactly what I needed. Thanks.

**Comment by DannyBen** [comment]
Cool. Releasing.

---

The `--force` and `--verbose` simply set an environment variable, so the author can do with it something if required.

https://github.com/DannyBen/rush-cli/blob/71f8aff07ca1a42c2e871946eb071d71dc21078b/src/snatch_command.sh#L5-L6
